// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzy1__-1nOl6rcpqKkg2LZWLuD9L-B38s',
    appId: '1:902819002888:web:e072b3dabfaacda36e2fbd',
    messagingSenderId: '902819002888',
    projectId: 'technostrelka-2026',
    authDomain: 'technostrelka-2026.firebaseapp.com',
    storageBucket: 'technostrelka-2026.firebasestorage.app',
    measurementId: 'G-REFWYVRMZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Z8W0Ga8XcUhpWrfdBnSBXLT8gn3ng3E',
    appId: '1:902819002888:android:60c53ad4feb67f5e6e2fbd',
    messagingSenderId: '902819002888',
    projectId: 'technostrelka-2026',
    storageBucket: 'technostrelka-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAM7JMQ_Pnwno9BV6saq5YjntvGTyiWYc',
    appId: '1:902819002888:ios:4b3946d3cb87c79d6e2fbd',
    messagingSenderId: '902819002888',
    projectId: 'technostrelka-2026',
    storageBucket: 'technostrelka-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAM7JMQ_Pnwno9BV6saq5YjntvGTyiWYc',
    appId: '1:902819002888:ios:4b3946d3cb87c79d6e2fbd',
    messagingSenderId: '902819002888',
    projectId: 'technostrelka-2026',
    storageBucket: 'technostrelka-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzy1__-1nOl6rcpqKkg2LZWLuD9L-B38s',
    appId: '1:902819002888:web:550187c55a13d9b66e2fbd',
    messagingSenderId: '902819002888',
    projectId: 'technostrelka-2026',
    authDomain: 'technostrelka-2026.firebaseapp.com',
    storageBucket: 'technostrelka-2026.firebasestorage.app',
    measurementId: 'G-J57ZVBMJ2L',
  );
}
